version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_encuentros
    ports:
      - "5673:5672"    # AMQP
      - "15673:15672"  # Panel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks: [appnet]

  postgres:
    image: postgres:latest
    container_name: pg_encuentros
    environment:
      POSTGRES_DB: encuentros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: America/Guayaquil
    ports:
      - "5434:5432"           # un solo puerto en tu host
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d   # scripts de creación de esquemas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d encuentros"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks: [appnet]

volumes:
  pg_data:

networks:
  appnet:
    driver: bridge
